### ISSUE TITLE
中文菜单排列无分级

### ISSUE THREAD

**Issue by jiahe224** [chwt163/Mpv.netRrightClickMenuCN#2]
1. 在程序所在目录里放置 input 后可显示中文，但无分级排列，所有选项都在一级目录
2. 主题无效，且鼠标移动到底部时不出现暂停栏

**Comment by chwt163** [comment]
不是放程序目录，是程序目录里面的 portable_config 文件夹
直接从 mpv.net 的右键菜单中打开配置文件夹： Settings > Open Config Folder，打开的就是 portable_config 文件夹

主题也是放 portable_config 里面的 scripts 和 script-opts 两个文件夹
按说明1234一步一步再试试？
